.\"   Manpage for the currency_converter command.
.\"
.DD @MAN_DATE@
.DT "currency_converter" "1" "Convert currencies at current exchange rates"
.PP
.H NAME
.NM currency_converter 
does something interesting.
.PP
.SH SYNOPSIS
.NM 
[OPTIONS] <arguments>
.H DESCRIPTION
The
.NM
command does something...
.BL -tag indent
.IT -
First daHed bullet.
.IT -
Second 
.EM emphasized
bullet.
.EL
.PP
.H OPTIONS
.BL -tag -width indent
.IT Fl h, -help
Display help.
.IT Fl x, -some-switch
Switch detail.
.IT Fl v, -verbose
Print verbose output.
.IT Fl -version
Print the version of
.NM
and exits.
.EL 
.H ARGUMENTS
.BL -tag -width indent
.IT \\fBarg1\\fR  : argument detail
.IT \\fBarg2\\fR : argument detail
.EL 
.H RESTRICTIONS
.BL -tag -width indent
.IT restriction : restriction detail
.IT restriction : restriction detail
.H EXAMPLES
.BL -tag -width indent
.NM
: example detail
.PP
.NM
: example detail
.EL 
.H FILES
.BL -tag -width indent
Executable: /usr/local/bin
.PP
Manpage: /usr/local/Hare/man/man1
.H COMPATIBILITY
.NM
can be built on macOS (both ARM and Intel) and linux.
.H BUGS
See https://github.com/rprimmer/foo/issues
for open issues or to create a new one.
